const mockInfoProjects = () => {[
    {
        "id": "6",
        "name": "Volcán Ajusco",
        "description": "",
        "status": "2",
        "clientid": "4",
        "billing_type": "2",
        "start_date": "2020-04-13",
        "deadline": null,
        "project_created": "2020-04-13",
        "date_finished": null,
        "progress": "0",
        "progress_from_tasks": "1",
        "project_cost": "0.00",
        "project_rate_per_hour": "0.00",
        "estimated_hours": "100.00",
        "addedfrom": "3",
        "userid": "4",
        "company": "Monitores S.A.",
        "vat": "",
        "phonenumber": "3327928322",
        "country": "142",
        "city": "",
        "zip": "45070",
        "state": "Jalisco",
        "address": "Matute Remus 1520",
        "website": "",
        "datecreated": "2020-02-14 11:49:58",
        "active": "1",
        "leadid": null,
        "billing_street": "",
        "billing_city": "",
        "billing_state": "",
        "billing_zip": "",
        "billing_country": "0",
        "shipping_street": "",
        "shipping_city": "",
        "shipping_state": "",
        "shipping_zip": "",
        "shipping_country": "0",
        "longitude": null,
        "latitude": null,
        "default_language": null,
        "default_currency": "3",
        "show_primary_contact": "0",
        "stripe_id": null,
        "registration_confirmed": "1"
    },
    {
        "id": "5",
        "name": "Proyecto de manuel",
        "description": "",
        "status": "2",
        "clientid": "13",
        "billing_type": "2",
        "start_date": "2020-04-02",
        "deadline": "2020-04-30",
        "project_created": "2020-04-02",
        "date_finished": null,
        "progress": "0",
        "progress_from_tasks": "1",
        "project_cost": "0.00",
        "project_rate_per_hour": "100.00",
        "estimated_hours": "100.00",
        "addedfrom": "3",
        "userid": "13",
        "company": "Manuel Ram SA de CV",
        "vat": null,
        "phonenumber": "3344556677",
        "country": "142",
        "city": "Guadalajara",
        "zip": "12391",
        "state": "Jalisco",
        "address": "Calle Negro",
        "website": "",
        "datecreated": "2020-04-02 12:28:22",
        "active": "1",
        "leadid": "27",
        "billing_street": "Calle Negro",
        "billing_city": "Guadalajara",
        "billing_state": "Jalisco",
        "billing_zip": "12391",
        "billing_country": "142",
        "shipping_street": null,
        "shipping_city": null,
        "shipping_state": null,
        "shipping_zip": null,
        "shipping_country": "0",
        "longitude": null,
        "latitude": null,
        "default_language": "",
        "default_currency": "0",
        "show_primary_contact": "0",
        "stripe_id": null,
        "registration_confirmed": "1"
    },
    {
        "id": "4",
        "name": "Rancho Carne",
        "description": "",
        "status": "1",
        "clientid": "4",
        "billing_type": "2",
        "start_date": "2020-03-10",
        "deadline": "2020-03-31",
        "project_created": "2020-03-10",
        "date_finished": null,
        "progress": "0",
        "progress_from_tasks": "1",
        "project_cost": "0.00",
        "project_rate_per_hour": "0.00",
        "estimated_hours": "0.00",
        "addedfrom": "3",
        "userid": "4",
        "company": "Monitores S.A.",
        "vat": "",
        "phonenumber": "3327928322",
        "country": "142",
        "city": "",
        "zip": "45070",
        "state": "Jalisco",
        "address": "Matute Remus 1520",
        "website": "",
        "datecreated": "2020-02-14 11:49:58",
        "active": "1",
        "leadid": null,
        "billing_street": "",
        "billing_city": "",
        "billing_state": "",
        "billing_zip": "",
        "billing_country": "0",
        "shipping_street": "",
        "shipping_city": "",
        "shipping_state": "",
        "shipping_zip": "",
        "shipping_country": "0",
        "longitude": null,
        "latitude": null,
        "default_language": null,
        "default_currency": "3",
        "show_primary_contact": "0",
        "stripe_id": null,
        "registration_confirmed": "1"
    },
    {
        "id": "3",
        "name": "proyecto dentro de monitores",
        "description": "porque no salen los hitos?",
        "status": "2",
        "clientid": "4",
        "billing_type": "2",
        "start_date": "2020-02-17",
        "deadline": "2020-02-27",
        "project_created": "2020-02-17",
        "date_finished": null,
        "progress": "0",
        "progress_from_tasks": "1",
        "project_cost": "0.00",
        "project_rate_per_hour": "2000.00",
        "estimated_hours": "125.00",
        "addedfrom": "3",
        "userid": "4",
        "company": "Monitores S.A.",
        "vat": "",
        "phonenumber": "3327928322",
        "country": "142",
        "city": "",
        "zip": "45070",
        "state": "Jalisco",
        "address": "Matute Remus 1520",
        "website": "",
        "datecreated": "2020-02-14 11:49:58",
        "active": "1",
        "leadid": null,
        "billing_street": "",
        "billing_city": "",
        "billing_state": "",
        "billing_zip": "",
        "billing_country": "0",
        "shipping_street": "",
        "shipping_city": "",
        "shipping_state": "",
        "shipping_zip": "",
        "shipping_country": "0",
        "longitude": null,
        "latitude": null,
        "default_language": null,
        "default_currency": "3",
        "show_primary_contact": "0",
        "stripe_id": null,
        "registration_confirmed": "1"
    },
    {
        "id": "1",
        "name": "Consultoría 1",
        "description": "Es un demo",
        "status": "2",
        "clientid": "1",
        "billing_type": "2",
        "start_date": "2020-01-26",
        "deadline": "2020-03-31",
        "project_created": "2020-01-26",
        "date_finished": null,
        "progress": "0",
        "progress_from_tasks": "1",
        "project_cost": "0.00",
        "project_rate_per_hour": "100.00",
        "estimated_hours": "100.00",
        "addedfrom": "1",
        "userid": "1",
        "company": "Vasos SA de CV",
        "vat": "JDI89777PLD",
        "phonenumber": "3333333",
        "country": "142",
        "city": "Zapopan",
        "zip": "45053",
        "state": "Jalisco",
        "address": "Hidalgo 100",
        "website": "Ninguno",
        "datecreated": "2020-01-25 12:46:26",
        "active": "1",
        "leadid": null,
        "billing_street": "",
        "billing_city": "",
        "billing_state": "",
        "billing_zip": "",
        "billing_country": "0",
        "shipping_street": "",
        "shipping_city": "",
        "shipping_state": "",
        "shipping_zip": "",
        "shipping_country": "0",
        "longitude": null,
        "latitude": null,
        "default_language": null,
        "default_currency": "3",
        "show_primary_contact": "0",
        "stripe_id": null,
        "registration_confirmed": "1"
    }
]};

const mockInfoTasks = () => {[
    {
        "id": "6",
        "name": "Convertir cotización a factura",
        "description": "",
        "priority": "3",
        "dateadded": "2020-02-19 11:07:09",
        "startdate": "2020-02-19",
        "duedate": "2020-02-20",
        "datefinished": null,
        "addedfrom": "3",
        "is_added_from_contact": "0",
        "status": "4",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": "3",
        "rel_type": "estimate",
        "is_public": "0",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "0",
        "deadline_notified": "0"
    },
    {
        "id": "1",
        "name": "Enviarle el contrato y este es demo",
        "description": "Enviarle el contrato del presupuesto.",
        "priority": "2",
        "dateadded": "2020-01-25 12:57:29",
        "startdate": "2020-01-25",
        "duedate": "2020-01-26",
        "datefinished": null,
        "addedfrom": "1",
        "is_added_from_contact": "0",
        "status": "4",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": "2",
        "rel_type": "estimate",
        "is_public": "0",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "100.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "0",
        "deadline_notified": "0"
    },
    {
        "id": "25",
        "name": "nueva tarea",
        "description": "",
        "priority": "0",
        "dateadded": "2020-05-12 13:38:54",
        "startdate": "0000-00-00",
        "duedate": null,
        "datefinished": null,
        "addedfrom": "0",
        "is_added_from_contact": "0",
        "status": "4",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": null,
        "rel_type": null,
        "is_public": "1",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "0",
        "deadline_notified": "0"
    },
    {
        "id": "26",
        "name": "nueva tarea",
        "description": "",
        "priority": "0",
        "dateadded": "2020-05-12 13:39:43",
        "startdate": "0000-00-00",
        "duedate": null,
        "datefinished": null,
        "addedfrom": "0",
        "is_added_from_contact": "0",
        "status": "4",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": null,
        "rel_type": null,
        "is_public": "1",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "0",
        "deadline_notified": "0"
    },
    {
        "id": "27",
        "name": "nueva tarea",
        "description": "",
        "priority": "0",
        "dateadded": "2020-05-12 13:40:18",
        "startdate": "0000-00-00",
        "duedate": null,
        "datefinished": null,
        "addedfrom": "0",
        "is_added_from_contact": "0",
        "status": "4",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": null,
        "rel_type": null,
        "is_public": "1",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "0",
        "deadline_notified": "0"
    },
    {
        "id": "28",
        "name": "nueva tarea",
        "description": "",
        "priority": "0",
        "dateadded": "2020-05-12 13:41:11",
        "startdate": "0000-00-00",
        "duedate": null,
        "datefinished": null,
        "addedfrom": "0",
        "is_added_from_contact": "0",
        "status": "4",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": null,
        "rel_type": null,
        "is_public": "1",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "0",
        "deadline_notified": "0"
    },
    {
        "id": "29",
        "name": "nueva tarea",
        "description": "",
        "priority": "0",
        "dateadded": "2020-05-12 13:41:45",
        "startdate": "0000-00-00",
        "duedate": null,
        "datefinished": null,
        "addedfrom": "0",
        "is_added_from_contact": "0",
        "status": "4",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": null,
        "rel_type": null,
        "is_public": "1",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "0",
        "deadline_notified": "0"
    },
    {
        "id": "30",
        "name": "nueva tarea",
        "description": "",
        "priority": "0",
        "dateadded": "2020-05-12 13:43:43",
        "startdate": "0000-00-00",
        "duedate": null,
        "datefinished": null,
        "addedfrom": "0",
        "is_added_from_contact": "0",
        "status": "4",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": null,
        "rel_type": null,
        "is_public": "1",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "0",
        "deadline_notified": "0"
    },
    {
        "id": "31",
        "name": "nueva tarea",
        "description": "",
        "priority": "0",
        "dateadded": "2020-05-12 13:43:53",
        "startdate": "0000-00-00",
        "duedate": null,
        "datefinished": null,
        "addedfrom": "0",
        "is_added_from_contact": "0",
        "status": "4",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": null,
        "rel_type": null,
        "is_public": "1",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "0",
        "deadline_notified": "0"
    },
    {
        "id": "32",
        "name": "nueva tarea",
        "description": "",
        "priority": "0",
        "dateadded": "2020-05-12 13:47:13",
        "startdate": "2020-05-05",
        "duedate": null,
        "datefinished": null,
        "addedfrom": "0",
        "is_added_from_contact": "0",
        "status": "4",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": null,
        "rel_type": null,
        "is_public": "1",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "0",
        "deadline_notified": "0"
    },
    {
        "id": "33",
        "name": "nueva tarea",
        "description": "",
        "priority": "0",
        "dateadded": "2020-05-12 13:48:09",
        "startdate": "2020-05-05",
        "duedate": null,
        "datefinished": null,
        "addedfrom": "0",
        "is_added_from_contact": "0",
        "status": "4",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": null,
        "rel_type": null,
        "is_public": "1",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "0",
        "deadline_notified": "0"
    },
    {
        "id": "47",
        "name": "nueva tarea 11",
        "description": "es una tarea con mas descripción",
        "priority": "1",
        "dateadded": "2020-05-12 15:05:47",
        "startdate": "2020-05-12",
        "duedate": null,
        "datefinished": null,
        "addedfrom": "1",
        "is_added_from_contact": "0",
        "status": "4",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": "3",
        "rel_type": "project",
        "is_public": "1",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "0",
        "deadline_notified": "0"
    },
    {
        "id": "51",
        "name": "nueva tarea 11",
        "description": "es una tarea con mas descripción",
        "priority": "1",
        "dateadded": "2020-05-12 15:17:08",
        "startdate": "2020-05-12",
        "duedate": null,
        "datefinished": null,
        "addedfrom": "1",
        "is_added_from_contact": "0",
        "status": "2",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": "3",
        "rel_type": "project",
        "is_public": "1",
        "billable": "0",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "0",
        "deadline_notified": "0"
    },
    {
        "id": "52",
        "name": "nueva tarea 11",
        "description": "es una tarea con mas descripción",
        "priority": "1",
        "dateadded": "2020-05-12 15:23:55",
        "startdate": "2020-05-12",
        "duedate": null,
        "datefinished": null,
        "addedfrom": "1",
        "is_added_from_contact": "0",
        "status": "2",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": "3",
        "rel_type": "project",
        "is_public": "1",
        "billable": "0",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "0",
        "deadline_notified": "0"
    },
    {
        "id": "53",
        "name": "nueva tarea 14",
        "description": "es una tarea con mas descripción",
        "priority": "1",
        "dateadded": "2020-05-12 15:26:00",
        "startdate": "2020-05-12",
        "duedate": null,
        "datefinished": null,
        "addedfrom": "1",
        "is_added_from_contact": "0",
        "status": "2",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": "3",
        "rel_type": "project",
        "is_public": "1",
        "billable": "0",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "0",
        "deadline_notified": "0"
    },
    {
        "id": "34",
        "name": "nueva tarea 2",
        "description": "",
        "priority": "0",
        "dateadded": "2020-05-12 13:48:57",
        "startdate": "2020-05-05",
        "duedate": null,
        "datefinished": null,
        "addedfrom": "0",
        "is_added_from_contact": "0",
        "status": "4",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": null,
        "rel_type": null,
        "is_public": "1",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "0",
        "deadline_notified": "0"
    },
    {
        "id": "54",
        "name": "nueva tarea 20",
        "description": "es una tarea con mas descripción",
        "priority": "1",
        "dateadded": "2020-05-14 13:38:30",
        "startdate": "2020-05-12",
        "duedate": null,
        "datefinished": null,
        "addedfrom": "1",
        "is_added_from_contact": "0",
        "status": "2",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": "3",
        "rel_type": "project",
        "is_public": "1",
        "billable": "0",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "0",
        "deadline_notified": "0"
    },
    {
        "id": "35",
        "name": "nueva tarea 3",
        "description": "",
        "priority": "0",
        "dateadded": "2020-05-12 13:50:10",
        "startdate": "2020-05-05",
        "duedate": null,
        "datefinished": null,
        "addedfrom": "0",
        "is_added_from_contact": "0",
        "status": "4",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": null,
        "rel_type": null,
        "is_public": "1",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "0",
        "deadline_notified": "0"
    },
    {
        "id": "36",
        "name": "nueva tarea 3",
        "description": "",
        "priority": "0",
        "dateadded": "2020-05-12 13:51:35",
        "startdate": "2020-05-05",
        "duedate": null,
        "datefinished": null,
        "addedfrom": "0",
        "is_added_from_contact": "0",
        "status": "4",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": null,
        "rel_type": null,
        "is_public": "1",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "0",
        "deadline_notified": "0"
    },
    {
        "id": "37",
        "name": "nueva tarea 3",
        "description": "es una tarea con mas descripción",
        "priority": "0",
        "dateadded": "2020-05-12 13:55:14",
        "startdate": "2020-05-05",
        "duedate": null,
        "datefinished": null,
        "addedfrom": "0",
        "is_added_from_contact": "0",
        "status": "4",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": null,
        "rel_type": null,
        "is_public": "1",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "0",
        "deadline_notified": "0"
    },
    {
        "id": "38",
        "name": "nueva tarea 3",
        "description": "es una tarea con mas descripción",
        "priority": "0",
        "dateadded": "2020-05-12 13:56:59",
        "startdate": "2020-05-05",
        "duedate": null,
        "datefinished": null,
        "addedfrom": "0",
        "is_added_from_contact": "0",
        "status": "4",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": null,
        "rel_type": null,
        "is_public": "1",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "0",
        "deadline_notified": "0"
    },
    {
        "id": "39",
        "name": "nueva tarea 3",
        "description": "es una tarea con mas descripción",
        "priority": "1",
        "dateadded": "2020-05-12 13:59:02",
        "startdate": "2020-05-05",
        "duedate": null,
        "datefinished": null,
        "addedfrom": "0",
        "is_added_from_contact": "0",
        "status": "4",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": null,
        "rel_type": null,
        "is_public": "1",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "0",
        "deadline_notified": "0"
    },
    {
        "id": "41",
        "name": "nueva tarea 3",
        "description": "es una tarea con mas descripción",
        "priority": "1",
        "dateadded": "2020-05-12 14:12:02",
        "startdate": "2020-05-05",
        "duedate": null,
        "datefinished": null,
        "addedfrom": "0",
        "is_added_from_contact": "0",
        "status": "4",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": null,
        "rel_type": null,
        "is_public": "1",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "0",
        "deadline_notified": "0"
    },
    {
        "id": "42",
        "name": "nueva tarea 3",
        "description": "es una tarea con mas descripción",
        "priority": "1",
        "dateadded": "2020-05-12 14:15:59",
        "startdate": "2020-05-05",
        "duedate": null,
        "datefinished": null,
        "addedfrom": "0",
        "is_added_from_contact": "0",
        "status": "4",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": null,
        "rel_type": null,
        "is_public": "1",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "0",
        "deadline_notified": "0"
    },
    {
        "id": "43",
        "name": "nueva tarea 9",
        "description": "es una tarea con mas descripción",
        "priority": "1",
        "dateadded": "2020-05-12 14:16:06",
        "startdate": "2020-05-05",
        "duedate": null,
        "datefinished": null,
        "addedfrom": "0",
        "is_added_from_contact": "0",
        "status": "4",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": null,
        "rel_type": null,
        "is_public": "1",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "0",
        "deadline_notified": "0"
    },
    {
        "id": "44",
        "name": "nueva tarea 9",
        "description": "es una tarea con mas descripción",
        "priority": "1",
        "dateadded": "2020-05-12 14:20:49",
        "startdate": "2020-05-05",
        "duedate": null,
        "datefinished": null,
        "addedfrom": "0",
        "is_added_from_contact": "0",
        "status": "4",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": "3",
        "rel_type": "project",
        "is_public": "1",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "0",
        "deadline_notified": "0"
    },
    {
        "id": "45",
        "name": "nueva tarea 9",
        "description": "es una tarea con mas descripción",
        "priority": "1",
        "dateadded": "2020-05-12 14:32:11",
        "startdate": "2020-05-05",
        "duedate": null,
        "datefinished": null,
        "addedfrom": "0",
        "is_added_from_contact": "0",
        "status": "4",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": "3",
        "rel_type": "project",
        "is_public": "0",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "0",
        "deadline_notified": "0"
    },
    {
        "id": "46",
        "name": "nueva tarea 9",
        "description": "es una tarea con mas descripción",
        "priority": "1",
        "dateadded": "2020-05-12 15:03:11",
        "startdate": "2020-05-05",
        "duedate": null,
        "datefinished": null,
        "addedfrom": "1",
        "is_added_from_contact": "0",
        "status": "4",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": "3",
        "rel_type": "project",
        "is_public": "1",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "0",
        "deadline_notified": "0"
    },
    {
        "id": "9",
        "name": "prueba de nueva tarea",
        "description": "",
        "priority": "2",
        "dateadded": "2020-04-13 12:02:31",
        "startdate": "2020-04-13",
        "duedate": null,
        "datefinished": "2020-04-18 12:01:23",
        "addedfrom": "3",
        "is_added_from_contact": "0",
        "status": "5",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": "5",
        "rel_type": "project",
        "is_public": "0",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "1",
        "deadline_notified": "0"
    },
    {
        "id": "10",
        "name": "REQS",
        "description": "",
        "priority": "2",
        "dateadded": "2020-04-13 12:02:35",
        "startdate": "2020-04-13",
        "duedate": null,
        "datefinished": null,
        "addedfrom": "1",
        "is_added_from_contact": "0",
        "status": "4",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": "5",
        "rel_type": "project",
        "is_public": "0",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "1",
        "deadline_notified": "0"
    },
    {
        "id": "50",
        "name": "revisar si mando el api",
        "description": "",
        "priority": "2",
        "dateadded": "2020-05-12 15:16:36",
        "startdate": "2020-05-12",
        "duedate": null,
        "datefinished": null,
        "addedfrom": "1",
        "is_added_from_contact": "0",
        "status": "4",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": "3",
        "rel_type": "project",
        "is_public": "0",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "1",
        "deadline_notified": "0"
    },
    {
        "id": "7",
        "name": "Se creó nuevo contacto 01",
        "description": "Contacto 01 seguimiento",
        "priority": "2",
        "dateadded": "2020-03-13 11:09:12",
        "startdate": "2020-03-13",
        "duedate": "2020-03-20",
        "datefinished": null,
        "addedfrom": "3",
        "is_added_from_contact": "0",
        "status": "4",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": "20",
        "rel_type": "lead",
        "is_public": "0",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "0",
        "deadline_notified": "1"
    },
    {
        "id": "4",
        "name": "se deriva de las fases",
        "description": "aqui estan las tareas de cada fase",
        "priority": "2",
        "dateadded": "2020-02-17 16:58:17",
        "startdate": "2020-02-17",
        "duedate": "2020-02-19",
        "datefinished": null,
        "addedfrom": "6",
        "is_added_from_contact": "0",
        "status": "4",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": "3",
        "rel_type": "project",
        "is_public": "1",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "3",
        "kanban_order": "0",
        "milestone_order": "1",
        "visible_to_client": "1",
        "deadline_notified": "0"
    },
    {
        "id": "5",
        "name": "sigue siendo parte de las fases",
        "description": "este serai la segunda linea de la grafica",
        "priority": "2",
        "dateadded": "2020-02-17 17:01:43",
        "startdate": "2020-02-20",
        "duedate": "2020-02-24",
        "datefinished": "2020-03-03 11:42:55",
        "addedfrom": "6",
        "is_added_from_contact": "0",
        "status": "5",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": "3",
        "rel_type": "project",
        "is_public": "0",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "3",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "1",
        "deadline_notified": "1"
    },
    {
        "id": "20",
        "name": "Tarea 02",
        "description": "",
        "priority": "2",
        "dateadded": "2020-04-24 11:07:26",
        "startdate": "2020-04-24",
        "duedate": null,
        "datefinished": null,
        "addedfrom": "3",
        "is_added_from_contact": "0",
        "status": "4",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": "3",
        "rel_type": "project",
        "is_public": "1",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "1",
        "deadline_notified": "0"
    },
    {
        "id": "21",
        "name": "Tarea 03",
        "description": "",
        "priority": "2",
        "dateadded": "2020-04-24 11:07:41",
        "startdate": "2020-04-24",
        "duedate": null,
        "datefinished": null,
        "addedfrom": "3",
        "is_added_from_contact": "0",
        "status": "4",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": "3",
        "rel_type": "project",
        "is_public": "0",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "1",
        "deadline_notified": "0"
    },
    {
        "id": "24",
        "name": "Tarea 05",
        "description": "",
        "priority": "2",
        "dateadded": "2020-04-24 11:10:26",
        "startdate": "2020-04-24",
        "duedate": null,
        "datefinished": null,
        "addedfrom": "3",
        "is_added_from_contact": "0",
        "status": "4",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": "3",
        "rel_type": "project",
        "is_public": "0",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "1",
        "deadline_notified": "0"
    },
    {
        "id": "48",
        "name": "tarea 12",
        "description": "",
        "priority": "2",
        "dateadded": "2020-05-12 15:07:06",
        "startdate": "2020-05-12",
        "duedate": null,
        "datefinished": null,
        "addedfrom": "1",
        "is_added_from_contact": "0",
        "status": "4",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": "3",
        "rel_type": "project",
        "is_public": "0",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "1",
        "deadline_notified": "0"
    },
    {
        "id": "49",
        "name": "tarea 12",
        "description": "",
        "priority": "2",
        "dateadded": "2020-05-12 15:08:24",
        "startdate": "2020-05-12",
        "duedate": null,
        "datefinished": null,
        "addedfrom": "1",
        "is_added_from_contact": "0",
        "status": "4",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": "3",
        "rel_type": "project",
        "is_public": "0",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "1",
        "deadline_notified": "0"
    },
    {
        "id": "22",
        "name": "Tarea 4",
        "description": "",
        "priority": "2",
        "dateadded": "2020-04-24 11:07:56",
        "startdate": "2020-04-24",
        "duedate": null,
        "datefinished": null,
        "addedfrom": "3",
        "is_added_from_contact": "0",
        "status": "4",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": "3",
        "rel_type": "project",
        "is_public": "0",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "1",
        "deadline_notified": "0"
    },
    {
        "id": "23",
        "name": "Tarea 6",
        "description": "",
        "priority": "2",
        "dateadded": "2020-04-24 11:08:10",
        "startdate": "2020-04-24",
        "duedate": null,
        "datefinished": null,
        "addedfrom": "3",
        "is_added_from_contact": "0",
        "status": "4",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": "3",
        "rel_type": "project",
        "is_public": "0",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "1",
        "deadline_notified": "0"
    },
    {
        "id": "8",
        "name": "Tarea de capacitación",
        "description": "",
        "priority": "1",
        "dateadded": "2020-04-02 12:20:39",
        "startdate": "2020-04-02",
        "duedate": null,
        "datefinished": null,
        "addedfrom": "3",
        "is_added_from_contact": "0",
        "status": "4",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": "27",
        "rel_type": "lead",
        "is_public": "0",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "0",
        "deadline_notified": "0"
    },
    {
        "id": "11",
        "name": "volcan tarea 1",
        "description": "",
        "priority": "2",
        "dateadded": "2020-04-13 12:40:53",
        "startdate": "2020-04-13",
        "duedate": null,
        "datefinished": "2020-04-13 12:56:31",
        "addedfrom": "3",
        "is_added_from_contact": "0",
        "status": "5",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": "6",
        "rel_type": "project",
        "is_public": "0",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "1",
        "deadline_notified": "0"
    },
    {
        "id": "12",
        "name": "volcan tarea 2",
        "description": "",
        "priority": "2",
        "dateadded": "2020-04-13 12:41:11",
        "startdate": "2020-04-13",
        "duedate": null,
        "datefinished": null,
        "addedfrom": "3",
        "is_added_from_contact": "0",
        "status": "4",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": "6",
        "rel_type": "project",
        "is_public": "0",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "1",
        "deadline_notified": "0"
    },
    {
        "id": "13",
        "name": "volcan tarea 3",
        "description": "",
        "priority": "2",
        "dateadded": "2020-04-13 12:41:25",
        "startdate": "2020-04-13",
        "duedate": null,
        "datefinished": null,
        "addedfrom": "3",
        "is_added_from_contact": "0",
        "status": "4",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": "6",
        "rel_type": "project",
        "is_public": "0",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "1",
        "deadline_notified": "0"
    },
    {
        "id": "14",
        "name": "volcan tarea 4",
        "description": "",
        "priority": "2",
        "dateadded": "2020-04-13 12:41:34",
        "startdate": "2020-04-13",
        "duedate": null,
        "datefinished": null,
        "addedfrom": "3",
        "is_added_from_contact": "0",
        "status": "4",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": "6",
        "rel_type": "project",
        "is_public": "0",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "1",
        "deadline_notified": "0"
    },
    {
        "id": "15",
        "name": "volcan tarea 5",
        "description": "",
        "priority": "2",
        "dateadded": "2020-04-13 12:41:45",
        "startdate": "2020-04-13",
        "duedate": null,
        "datefinished": null,
        "addedfrom": "3",
        "is_added_from_contact": "0",
        "status": "4",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": "6",
        "rel_type": "project",
        "is_public": "0",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "1",
        "deadline_notified": "0"
    },
    {
        "id": "16",
        "name": "volcan tarea 6",
        "description": "",
        "priority": "2",
        "dateadded": "2020-04-13 12:42:00",
        "startdate": "2020-04-13",
        "duedate": null,
        "datefinished": null,
        "addedfrom": "3",
        "is_added_from_contact": "0",
        "status": "4",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": "6",
        "rel_type": "project",
        "is_public": "0",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "1",
        "deadline_notified": "0"
    },
    {
        "id": "17",
        "name": "volcan tarea 7",
        "description": "",
        "priority": "2",
        "dateadded": "2020-04-13 12:48:04",
        "startdate": "2020-04-13",
        "duedate": null,
        "datefinished": "2020-04-23 13:56:35",
        "addedfrom": "3",
        "is_added_from_contact": "0",
        "status": "5",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": "6",
        "rel_type": "project",
        "is_public": "0",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "1",
        "deadline_notified": "0"
    },
    {
        "id": "18",
        "name": "volcan tarea 8",
        "description": "",
        "priority": "2",
        "dateadded": "2020-04-13 12:48:14",
        "startdate": "2020-04-13",
        "duedate": null,
        "datefinished": "2020-04-23 13:56:39",
        "addedfrom": "3",
        "is_added_from_contact": "0",
        "status": "5",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": "6",
        "rel_type": "project",
        "is_public": "0",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "1",
        "deadline_notified": "0"
    },
    {
        "id": "19",
        "name": "volcan tarea 9",
        "description": "",
        "priority": "2",
        "dateadded": "2020-04-13 12:48:28",
        "startdate": "2020-04-13",
        "duedate": null,
        "datefinished": "2020-04-13 12:57:03",
        "addedfrom": "3",
        "is_added_from_contact": "0",
        "status": "5",
        "recurring_type": null,
        "repeat_every": "0",
        "recurring": "0",
        "is_recurring_from": null,
        "cycles": "0",
        "total_cycles": "0",
        "custom_recurring": "0",
        "last_recurring_date": null,
        "rel_id": "6",
        "rel_type": "project",
        "is_public": "0",
        "billable": "1",
        "billed": "0",
        "invoice_id": "0",
        "hourly_rate": "0.00",
        "milestone": "0",
        "kanban_order": "0",
        "milestone_order": "0",
        "visible_to_client": "1",
        "deadline_notified": "0"
    }
]};

const mockInfoUsers = () => {
    {
    "staffid": "1",
    "email": "gabriela@4040apps.com",
    "firstname": "Gabriela",
    "lastname": "J",
    "facebook": "",
    "linkedin": "",
    "phonenumber": "333333",
    "skype": "",
    "password": "$2a$08$G047BVSuByPj86Js9hgP7u2EqE3qCrU.thNTr5HazMKR0mDEW8lTa",
    "datecreated": "2020-01-25 09:08:24",
    "profile_image": null,
    "last_ip": "148.243.83.90",
    "last_login": "2020-05-14 09:58:20",
    "last_activity": "2020-05-14 10:11:39",
    "last_password_change": "2020-04-13 03:19:21",
    "new_pass_key": "1be68fbf009ed20dd83c84777e2f1ce9",
    "new_pass_key_requested": "2020-01-26 13:54:13",
    "admin": "1",
    "role": "0",
    "active": "1",
    "default_language": null,
    "direction": null,
    "media_path_slug": null,
    "is_not_staff": "0",
    "hourly_rate": "0.00",
    "two_factor_auth_enabled": "0",
    "two_factor_auth_code": null,
    "two_factor_auth_code_requested": null,
    "email_signature": "",
    "mail_password": "Queteimport4",
    "last_email_check": null,
    "directivo": "1",
    "operativo": "0",
    "full_name": "Gabriela J",
    "permissions": []
}
};

export {mockInfoProjects, mockInfoTasks, mockInfoUsers};